"""add trip share_token

Revision ID: 34a2720be578
Revises: 3caafb9af9fb
Create Date: 2026-09-30 20:52:59.552303

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34a2720be578"
down_revision: str | Sequence[str] | None = "3caafb9af9fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trip", sa.Column("share_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_trip_share_token"), "trip", ["share_token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_share_token"), table_name="trip")
    op.drop_column("trip", "share_token")
    # ### end Alembic commands ###
