"""sync trip model: total_distance nullable, drop permit columns

Revision ID: af65a881b505
Revises: 8528f4b28b1e
Create Date: 2026-09-22 17:51:25.648124

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af65a881b505"
down_revision: str | Sequence[str] | None = "8528f4b28b1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trip", "total_distance", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("trip", "permit_required")
    op.drop_column("trip", "permit_details")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trip", sa.Column("permit_details", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("trip", sa.Column("permit_required", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column("trip", "total_distance", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
